services:
  - type: web
    name: laravel-app
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: DB_HOST
        fromService:
          type: pserv
          name: mysql
          property: host
      - key: DB_DATABASE
        value: laravel
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        generateValue: true

  - type: pserv
    name: mysql
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: MYSQL_DATABASE
        value: laravel
      - key: MYSQL_ROOT_PASSWORD
        generateValue: true